### ISSUE TITLE
Morte's initial dialog is not modified

### ISSUE THREAD

**Issue by modo-lv** [Argent77/PST-UB-reloaded#9]
Mod version 2.3 and PT:EE version 3.1.4.0. Mod installs without issue, but Morte's initial dialog is unchanged from vanilla game.

**Comment by Argent77** [comment]
This is intended if you install the "All recommended components" option since the initial dialog content is repeated in future conversations with Morte or other companions.

You can choose Morte's more verbose dialog version if you skip the install-all component and choose the respective option of the "Restored More Morte Mortuary Moments" component. More details can be found in the [readme](https://argent77.github.io/PST-UB-reloaded/index.html#components).

**Comment by modo-lv** [comment]
Ah, I see, my bad, I only skimmed the readme and missed that detail. Thanks for the explanation.

It may however be helpful to not have the initial dialog as the first screenshot of the mod on the forum page, if it's not included in the default install. Otherwise it seems like the quickest way to verify that the mod is correctly installed and working.
